# Generated by Django 2.0.6 on 2019-03-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymMemberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('imageURL', models.CharField(default='', max_length=800)),
            ],
        ),
    ]
